### ISSUE TITLE
[digitalocean] removing it to it's own gem

### ISSUE THREAD

**Issue by jjasghar** [fog/fog#3869]
Hi all! With the help of @geemus, we have a repo for fog-digitalocean now.

https://github.com/fog/fog-digitalocean

I've done an initial import but we still need to verify everything is setup correctly.

If you'd like to help don't hesitate to reach out.

- [ ] Pass tests
- [ ] Remove digital ocean from fog/fog
- [ ] Add to fog/fog slurp in fog-digitalocean
- [ ] Clean up readme

**Comment by geemus** [comment]
Thanks!

**Comment by plribeiro3000** [comment]
@jjasghar What are we missing to finish the extraction?
Can i help with something?

**Comment by 01sas** [comment]
As I can see for now code is only moved to separate repository and at the same time still remain in this. So it is required to remove it from here, as it contains bugs.

But I am not a Ruby developer and not avare about details of dependency management and so on, so may be something also is required.

**Comment by plribeiro3000** [comment]
Will try to move forward with this during the weekend then.
Will keep you posted.

**Comment by bsedat** [comment]
There are unfortunately some bugs in the DigitalOcean integration with the latest Fog release (v1.38.0). I believe I fixed them in fog/fog but we haven't backported anything to fog-digitalocean yet.

@01sas Does the error occur if you use Github's master branch of fog/fog?
Also you should revoke that DigitalOcean API token if it is real or still active.

**Comment by 01sas** [comment]
No, this bug with ssh keys works in fog-digitalocean but does not work in fog.

**Comment by 01sas** [comment]
> @01sas Does the error occur if you use Github's master branch of fog/fog?
Yes, this bug still occur for master branch. I provide a link to the problem code which is still in master branch.

> Also you should remove/revoke that DigitalOcean API token if it is real or still active.
Thanks for pointing this. Key removed and revoked.

**Comment by jjasghar** [comment]
Sorry about the radio silence on this. I pulled the majority of the gem out, but i think i hit a snag.

I've been locked up in my day-to-day job lately, and would love some help if finishing this off.

We should probably backport everything to the fog-digitalocean gem and remove all the references from fog/fog so something like this doesn't happen again.

Thoughts?

**Comment by h0lyalg0rithm** [comment]
@jjasghar I worked with this project for a while.I can you on it from tomorrow.

**Comment by jjasghar** [comment]
Sounds good. I got extremely close to getting all the tests passing, but i got pulled away.

After that we need to push `fog-digitalocean` to rubygems and put the PR in to remove it from fog completely.

Then we should be back on track. Thanks!

**Comment by h0lyalg0rithm** [comment]
If you have some code working please push to the repo.I will send a PR tomorrow

**Comment by jjasghar** [comment]
Already there: https://github.com/fog/fog-digitalocean

**Comment by h0lyalg0rithm** [comment]
Thanks, I thought there were more 👍

**Comment by geemus** [comment]
Thanks! Going to go ahead and close this in favor of the other newer PRs from @h0lyalg0rithm which are nearly complete.
