### ISSUE TITLE
Fog Build Failure

### ISSUE THREAD

**Issue by bilal-naeem-confiz** [fog/fog#3914]
Hi
Fog CI build is failing due to issues with some providers. It is failing for all ruby versions.
[Travis](https://travis-ci.org/fog/fog)
How are we going to fix these build errors?

**Comment by geemus** [comment]
I believe I just pushed a fix for the error that was coming up there here: https://github.com/fog/fog/commit/994fc66d3bb5e8e1ee90292776d58042e9a73595

**Comment by bilal-naeem-confiz** [comment]
Fog CI build is still failing even after that fix
[Travis](https://travis-ci.org/fog/fog)

**Comment by Temikus** [comment]
Yeah, I think https://github.com/fog/fog-digitalocean/pull/12 needs to be released with a gem first.

@geemus @plribeiro3000 - Can you guys push a new version to rubygems? I don't have push access :(

**Comment by plribeiro3000** [comment]
Sure. Let me see about it.

**Comment by plribeiro3000** [comment]
Released as `0.2.0`.

**Comment by Temikus** [comment]
@plribeiro3000 Thanks!
Looks like we need https://github.com/fog/fog-core/pull/197 from fog-core too.

@geemus Can you release a new fog-core when you have the chance? I can bump up the spec myself.

**Comment by geemus** [comment]
@Temikus fog-core has now also been released, `v1.43.0`.

**Comment by plribeiro3000** [comment]
I believe `fog-core` was released after this happened so we don't need to keep this open.

Will close and block this in favor of #3933.

**Comment by geemus** [comment]
Thanks!
